//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MameTools.Net48.Resources {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MameTools.Net48.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Bios.
        /// </summary>
        internal static string Bios {
            get {
                return ResourceManager.GetString("Bios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a CHD xml file loading.
        /// </summary>
        internal static string ChdXmlLoading {
            get {
                return ResourceManager.GetString("ChdXmlLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Detected release {0} build {1}.
        /// </summary>
        internal static string DetectedReleaseBuild {
            get {
                return ResourceManager.GetString("DetectedReleaseBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Device.
        /// </summary>
        internal static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a File generation failed.
        /// </summary>
        internal static string FileGenerationFailed {
            get {
                return ResourceManager.GetString("FileGenerationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a File {0} not found.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invalid XML node relation: node {0} required by  {1}.
        /// </summary>
        internal static string InvalidXmlNodeRelation {
            get {
                return ResourceManager.GetString("InvalidXmlNodeRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Machines XML file creation.
        /// </summary>
        internal static string MachinesFileCreation {
            get {
                return ResourceManager.GetString("MachinesFileCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Machines XML file loading.
        /// </summary>
        internal static string MachinesFileLoading {
            get {
                return ResourceManager.GetString("MachinesFileLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Mame machine {0} not found.
        /// </summary>
        internal static string MameMachineNotFound {
            get {
                return ResourceManager.GetString("MameMachineNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Mechanical.
        /// </summary>
        internal static string Mechanical {
            get {
                return ResourceManager.GetString("Mechanical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error loading file {0}: root node {1} not found!.
        /// </summary>
        internal static string MissingRootNode {
            get {
                return ResourceManager.GetString("MissingRootNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Samples file loading.
        /// </summary>
        internal static string SamplesFileLoading {
            get {
                return ResourceManager.GetString("SamplesFileLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Software XML file creation.
        /// </summary>
        internal static string SoftwareFileCreation {
            get {
                return ResourceManager.GetString("SoftwareFileCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Software XML file loading.
        /// </summary>
        internal static string SoftwareFileLoading {
            get {
                return ResourceManager.GetString("SoftwareFileLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Software hash XML file loading.
        /// </summary>
        internal static string SoftwareHashFileLoading {
            get {
                return ResourceManager.GetString("SoftwareHashFileLoading", resourceCulture);
            }
        }
    }
}
